### PR TITLE
Feature remove provider_id references 

### PR DESCRIPTION
**Pull request by kjgarza**
## Purpose

Remove references to provider when creating and authenticating a report. 

closes: https://github.com/datacite/sashimi/issues/123

## Approach

By adding this change client transfer do not affect reports.

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

## Status
- [x] Ready for Review

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by kjgarza** [comment]
yes, sorry forgot to mention that. 

All the interactions use `uid` for the authorisation. See new update. 

However, the problem with using `uid` is that the table already include a column named `uid`  for the report key.: https://github.com/datacite/sashimi/blob/d48462c/db/schema.rb#L88

I am keeping that separated in the table.

**Comment by mfenner** [comment]
What column is now used to store the `uid` of the authenticated user? If uid is already taken, why not use something like `user_id`?

**Comment by kjgarza** [comment]
we use client_id

**Comment by mfenner** [comment]
It should be easy to change to `user_id` to avoid any confusion in the future. There are not so many records in the database that the migration would be a problem.

**Comment by kjgarza** [comment]
But why changing the `client_id` to a different label?
This is definitely the client_id in all other APIs. Plus its currently internal to this API. Moreover, it doesn't affect the goal of this PR (removing the reliance on the `provider.client` naming). 
On top of that, it would also break a public interface (filtering by client_id). 
 It seems so unnecessary when user_id is a made-up label, don't you think?

**Pull request merged**
